### ISSUE TITLE
Major update for a PR (here or carriedaymont/growthcleanr) ?

### ISSUE THREAD

**Issue by mcanouil** [mitre/growthcleanr#14]
Hi,

I am going to use this package a lot and at first, I used the scripts from the article.
I have forked and make (a lot of) changes and I was wondering where I should do the PR in the main repository or in this one (seems more active)?

https://github.com/mcanouil/growthcleanr/tree/optimdep
``` 
==> devtools::test()

Loading growthcleanr
Testing growthcleanr
✓ |  OK F W S | Context
✓ |   5       | cdc [0.7 s]
✓ |   8       | cleangrowth [16.8 s]
✓ |  76       | utils [29.4 s]

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 46.8 s

OK:       89
Failed:   0
Warnings: 0
Skipped:  0
```

Best regards,

Below are the changes and possible changes to come.

* * *

### Changelog: 
* Includes the proposed changes from https://github.com/carriedaymont/growthcleanr/pull/6
* Includes the proposed changes from https://github.com/carriedaymont/growthcleanr/pull/7
* Includes the proposed changes from https://github.com/mitre/growthcleanr/pull/7
* Uses actual boolean variable install of shortcuts to avoid the behaviour below:
    ``` r
    T <- 25
    T
    #> [1] 25
    TRUE <- 25
    #> Error in TRUE <- 25: invalid (do_set) left-hand side to assignment
    ```
* Uses `setkeyv` instead of `setkey` to reduce the global variables checks warnings (if the package is at some point intended to be deployed on CRAN)
* Refactoring to make the code more readable and consistent across the package (except `tests/`)
* Split big R files into several ones per functions, to ease the update and changes, which with several thousands lines is hard.
* Remove dependency to `Hmisc`, `dplyr` and `tidyr`, which was not needed since the main framework is `data.table`.
* Add `stats` in `Imports`.
* Add `R (>= 3.6.0)` in `Depends`.
* Complete rewrite of `read_anthro()` and `long_wide()`.
* In `Dockerfile`, now dependencies are installed from `growthcleanr` in one command.

### To do (maybe):
* `README-adjustcarryforward.md` as a vignette.
    ``` r
    > checking top-level files ... NOTE
      Non-standard file/directory found at top level:
        ‘README-adjustcarryforward.md’
    ```
* Fix `"no visible binding for global variable"` from `data.table`.
* Fix documentation issues
    ``` r
    W  checking Rd \usage sections ...
       Undocumented arguments in documentation object 'cleangrowth'
         ‘height.tolerance.cm’
       
       Undocumented arguments in documentation object 'long_wide'
         ‘long_df’ ‘clean_value’
       Documented arguments not in \usage in documentation object 'long_wide':
         ‘data’
       
       Undocumented arguments in documentation object 'split_input'
         ‘min_nrow’
       Documented arguments not in \usage in documentation object 'split_input':
         ‘min_row’
    ```
* Fix examples errors related to code changes.
    ``` r
    > checking examples ... ERROR
    ```
* Reduce complexity of `cleanbatch()`, `cleangrowth()` and `adjustcarryforward() which share a lot of code.
* Replace the following code (same approach in differents places) using `findInterval()`.
    ``` r
    # 15h.	Generate variable whoinc_age_ht based on values of d_agedays_ht according the the following table
    #   d_agedays_ht	whoinc_age_ht
    #   20-45	        1
    #   46-75	        2
    #   76-106	      3
    #   107-152	      4
    #   153-198	      6
    #   All others	  missing
    df[, whoinc.age.ht := ifelse(delta.agedays.next < 20,
      NA,
      ifelse(
        delta.agedays.next <= 45,
        1,
        ifelse(
          delta.agedays.next <= 75,
          2,
          ifelse(
            delta.agedays.next <= 106,
            3,
            ifelse(
              delta.agedays.next <= 152,
              4,
              ifelse(delta.agedays.next <= 198, 6, NA)
            )
          )
        )
      )
    )]
    ```
* Update documentation to use reference across functions to avoid repeating information and miss one when there is an update.

**Comment by dchud** [comment]
Thanks @mcanouil ! It's great to know that you're working with this package. You've done a lot here, so it might take us a little time to review, but wanted to let you know that we're taking a look.

Regarding where to send it, we have been tweaking our workflow as we go and are switching to sending PRs to @carriedaymont's repo - we are working with her on these changes and can help triage PRs there perhaps more easily than on this fork.

**Comment by mcanouil** [comment]
I made the PR (https://github.com/carriedaymont/growthcleanr/pull/9) which includes 'few' more changes.

**Comment by dchud** [comment]
Closing here; discussion continued at https://github.com/carriedaymont/growthcleanr/pull/9.
